services:
  clientemqtt:
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SERVIDOR=${SERVIDOR}
      - TOPICO=${TOPICO}
    restart: unless-stopped